syntax = "proto3";

package monitoring.configuration.v1;

import "google/protobuf/timestamp.proto";

option go_package = "github.com/KRUTONIK/web-service-monitoring/contracts/gen/go/monitoring/configuration/v1;configurationv1";

service ConfigurationService {
  rpc GetSnapshot(GetSnapshotRequest) returns (GetSnapshotResponse);
}

message GetSnapshotRequest {}

message GetSnapshotResponse {
  repeated Service services = 1;
}

message Service {
  string id = 1;
  string url = 2;
  bool enabled = 3;
  int64 version = 4;
  google.protobuf.Timestamp updated_at = 5;
}
